name: build cmake CI

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Build program
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}
      run: |       
        execute_process(COMMAND cmake project -DBOOST_ROOT=%BOOST_ROOT_1_72_0%
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad cmake project : ${result}")
        endif() 
        
        execute_process(COMMAND dir
          OUTPUT_VARIABLE out
        )
        message(STATUS "dir after init = ${out}") 
        
        execute_process(COMMAND cmake --build .
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad cmake --build : ${result}")
        endif()
        
    - name: Test program
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}
      run: |
        set(SRC_DIR "project\\product\\rule_samples")
        set(DEST_DIR "test\\Debug\\rule_samples")
        message(STATUS "src dir= ${SRC_DIR}, dest_dir= ${DEST_DIR}")
        
        execute_process(COMMAND xcopy /I /Y ${SRC_DIR} ${DEST_DIR}
          RESULT_VARIABLE result
          OUTPUT_VARIABLE out
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Copy Test data failed : ${result}, ${out}")
        endif()
        
        execute_process(COMMAND dir ${DEST_DIR}
          RESULT_VARIABLE result
          OUTPUT_VARIABLE out
        )
        message(FATAL_ERROR "dir dest : ${result}, ${out}")

        execute_process(COMMAND ./test/Debug/test.exe
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Test failed : ${result}")
        endif()
