name: build cmake CI

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2
    - name: Build program
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}
      run: |       
        execute_process(COMMAND cmake project -DBOOST_ROOT=%BOOST_ROOT_1_72_0% -B build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad cmake project : ${result}")
        endif() 
        
        execute_process(COMMAND dir
          OUTPUT_VARIABLE out
        )
        message(STATUS "dir after init = ${out}") 
        
        execute_process(COMMAND cmake --build build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad cmake --build : ${result}")
        endif()
        
    - name: Test program
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}
      run: |
        set(SRC_DIR "project\\product\\rule_samples")
        set(DEST_DIR "build\\test\\Debug\\rule_samples")
        message(STATUS "src dir= ${SRC_DIR}, dest_dir= ${DEST_DIR}")
        
        execute_process(COMMAND xcopy /I /Y ${SRC_DIR} ${DEST_DIR}
          RESULT_VARIABLE result
          OUTPUT_VARIABLE out
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Copy Test data failed : ${result}, ${out}")
        endif()
        
        execute_process(COMMAND build/test/Debug/test.exe
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Test failed : ${result}")
        endif()
        
    - name: Create export
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}
      run: |
        execute_process(COMMAND cmake --install build  --config Debug --prefix .
          RESULT_VARIABLE result
          OUTPUT_VARIABLE out
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Install to export failed : ${result}, ${out}")
        endif()
        execute_process(COMMAND dir export
          OUTPUT_VARIABLE out
        )        
        message(STATUS "dir export = ${out}") 

    - name: Pack exort
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}
      run: |
        execute_process(COMMAND cmake -E tar cjfv ${{ matrix.config.artifact }} export
          RESULT_VARIABLE result
          OUTPUT_VARIABLE out
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Pack export failed : ${result}, ${out}")
        endif()

    - name: Upload export
      uses: actions/upload-artifact@v1
      with:
        path: ./${{ matrix.config.artifact }}
        name: ${{ matrix.config.artifact }}


  release:
    if: contains(github.ref, 'tags/v')
    runs-on: windows-latest
    needs: build

    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Store Release url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url
    - uses: actions/upload-artifact@v1
      with:
        path: ./upload_url
        name: upload_url

publish:
    if: contains(github.ref, 'tags/v')
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest
          }
    needs: release

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url

    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./${{ matrix.config.artifact }}
        asset_name: ${{ matrix.config.artifact }}
        asset_content_type: application/x-gtar
