name: build cmake CI

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release


jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    #- uses: actions/checkout@v2
    - name: Build program
      shell: cmake -P {0}
      run: |      
        #execute_process(COMMAND cd ${GITHUB_WORKSPACE})
        #execute_process(COMMAND cd ..)
        execute_process(COMMAND mkdir build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad mkdir build status")
        endif() 
        
        execute_process(COMMAND dir
          OUTPUT_VARIABLE out
        )
        message(STATUS "dir after mkdir = ${out} and ${GITHUB_WORKSPACE}")
        
        #execute_process(COMMAND icacls  ${GITHUB_WORKSPACE}build /grant Everyone:F
        #  RESULT_VARIABLE result
        #)
        #if (NOT result EQUAL 0)
        #  message(FATAL_ERROR "Bad icacls status")
        #endif() 
        
        #execute_process(COMMAND cd ${GITHUB_WORKSPACE}build
        execute_process(COMMAND cd build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad cd build dir status")
        endif() 
        execute_process(COMMAND dir
          OUTPUT_VARIABLE out
        )
        message(STATUS "dir after cd build = ${out}")        
        execute_process(COMMAND cmake ../project -DBOOST_ROOT=%BOOST_ROOT_1_72_0%)
        execute_process(COMMAND cmake --build .
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad cmake --build status")
        endif()
